<?php

/* AUTH */
CONST AUTH_DELETE = 'AUTH_DELETE';
CONST AUTH_MODIFY = 'AUTH_MODIFY';
CONST AUTH_DELETE_ACTIONS = 'AUTH_DELETE_ACTIONS';
CONST AUTH_DELETE_GROUPS = 'AUTH_DELETE_GROUPS';
CONST AUTH_MODIFY_GROUPS = 'TREE_U_AUTH';
CONST AUTH_VIEW = 'AUTH_VIEW';
CONST AUTH_MODIFY_USERS = 'AUTH_MODIFY_USERS';
CONST AUTH_MODIFY_RANK = 'AUTH_MODIFY_RANK';
CONST AUTH_SET = 'AUTH_SET';
CONST AUTH_SET_ACTIONS = 'AUTH_SET_ACTIONS';
CONST AUTH_SET_GROUPS = 'AUTH_SET_GROUPS';
