<?php
const INPUT_VALIDATION_FAILURE = 'INPUT_VALIDATION_FAILURE';
const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
const OBJECT_AUTHENTICATION_FAILURE = 'OBJECT_AUTHENTICATION_FAILURE';
const WRONG_CSRF_TOKEN = 'WRONG_CSRF_TOKEN';
const SECURITY_FAILURE = 'SECURITY_FAILURE';


