<?php
const API_DISABLED = 'API_DISABLED';
const INPUT_VALIDATION_FAILURE = 'INPUT_VALIDATION_FAILURE';
const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
const OBJECT_AUTHENTICATION_FAILURE = 'OBJECT_AUTHENTICATION_FAILURE';
const WRONG_CSRF_TOKEN = 'WRONG_CSRF_TOKEN';
const SECURITY_FAILURE = 'SECURITY_FAILURE';
const RATE_LIMIT_REACHED = 'RATE_LIMIT_REACHED';
const CAPTCHA_MISSING = 'CAPTCHA_MISSING';
const CAPTCHA_INVALID = 'CAPTCHA_INVALID';
const CAPTCHA_ALREADY_VALIDATED = 'CAPTCHA_ALREADY_VALIDATED';
const CAPTCHA_SERVER_FAILURE = 'CAPTCHA_SERVER_FAILURE';


